### PR TITLE
Added FAQ reference to #NoBans, which is way down at the bottom of th…

### PR DESCRIPTION
**Pull request by jonathonbarton**
#88 Added reference to #nobans from the homepage to the FAQ docs.
If you already know about FiveM or hear about it from a friend, #nobans is an easy thing to miss because it's below the comparisons way at the bottom of the page.
Adding it to the FAQ is a layer of idiot proofing.
Pull request submitted by one of said idiots. :D

### CODE REVIEW

**Comment by cerium-cfx** [comment]
I'm okay with this PR except the weird change to the project settings and file in `.vs` :(

Please remove these.

**Comment by cerium-cfx** [comment]
Changes have been requested 2.5 months ago. Are you going to remove the changes to the project settings and the sqlite db?

**Comment by jonathonbarton** [comment]
At some point I had to reset my PC from scratch and haven't re-set up the tools to do this work since.

**Comment by rjmxtechnology** [comment]
Not sure why he closed this but I made a new PR with the requested changes as it shows above

**Comment by jonathonbarton** [comment]
I closed it because I don't have the ability to make the requested changes myself anymore, per my comment above. :(

**Comment by rjmxtechnology** [comment]
@jonathonbarton You could have just made a new fork and pasted the changes to the client-faq file just like I did but it's not that big of a deal

@stannum-cfx I made a new PR with the requested changes as it shows above

**Pull request closed without merging**
