### PR TITLE
Removed reference to deleted Discord channel

### PR DESCRIPTION
**Pull request by HaxersAlwaysWin**

### CODE REVIEW

**Comment by rex2630** [comment]
WTF? That discrod does still exists...!

**Comment by manups4e** [comment]
i think this is mainly to mitigate all those same questions that are made everyday (every 10 mins i'd add)
and in this way using the forum they could notice some threads with maybe the same question and already answered.

**Comment by hojgr** [comment]
idk, dont like it. While we are at it, the symbols link is dead - https://runtime.fivem.net/client/symbols/

**Comment by Something-Debug** [comment]
What do you mean the symbols link is dead? It works as intended.

**Comment by manups4e** [comment]
he means this 
image

**Comment by Disquse** [comment]
> he means this
This is fine because that link is supposed to be used in IDEs which generating full path to symbol files.

**Comment by cerium-cfx** [comment]
The Discord invite link still works. We can update it with the vanity URL now though. As for the channel, yes that doesn't exist anymore but instead if called `#fxserver-support`.

If you'd like, update the PR with the info given above please.

**Pull request closed without merging**
