### PR TITLE
Update resource-manifest.md

### LINKED ISSUE #100: Resource manifest
both of the manifest links are 404

### PR DESCRIPTION
**Pull request by nathanctech**
Fixes #100 (link to natives page rather than wiki)

### CODE REVIEW

**Comment by cerium-cfx** [comment]
Instead of using a static link, I'd like to see the use of `{{<native "GET_RESOURCE_METADATA">}}` as used for `LOAD_RESOURCE_FILE` [here](https://github.com/citizenfx/fivem-docs/blob/master/content/docs/server-manual/migrating-from-citmp.md)

I noticed all links using `"wikilink"` are outdated. I will fix all other links and will leave this issue open for you to edit it with the changes requested above.

**Comment by cerium-cfx** [comment]
This is now 2.5 months old and no changes :(

**Comment by nathanctech** [comment]
Made requested changes. Entirely fell off my radar.

**Comment by technetium-cfx** [comment]
Fixed in c6c4503.

**Pull request closed without merging**
