### PR TITLE
Updated the C# setup guide

### PR DESCRIPTION
**Pull request by SaSiNO97**
- Updated the guide to Visual Studio 2019
- Added a bunch of new screenshots
- Added a few tips about shared projects and more
- Added NuGet instructions

### CODE REVIEW

**Comment by blattersturm** [comment]
While the effort put into this is appreciated, it still has a lot of the flaws the old guide did. It still makes you end up with an old-style .csproj file, it still mentions long-since-outdated settings, and should _technically_ be minimized to 2 steps only if VS were to have a GUI for modern .NET templates.

**Comment by manups4e** [comment]
i would suggest using this https://cookbook.fivem.net/2020/02/24/try-the-new-citizenfx-c-templates-for-fivem/
for the new C# guide..

**Comment by blattersturm** [comment]
See also: https://devblogs.microsoft.com/dotnet/net-cli-templates-in-visual-studio/

**Comment by SaSiNO97** [comment]
Hey. I didn't mean to make "the new C# guide", I just meant to update it from VS 2017 to VS 2019 and the usage of NuGet package instead of copying and pasting files manually. I still think this revision should be published, after fixing the wrong framework reference versions; I'll be happy to fix those mistakes if you tell me what the correct framework reference versions are.

**Comment by SaSiNO97** [comment]
Ok great, so I guess this is what happens when you decide to waste two hours of your time trying to contribute to a project. It just gets forgotten in a pull request page. Gotcha. 
This **strongly discourages** anyone from contributing to the docs.
You should either give public write access, or at least accept all pull requests (except vandalism), and if you don't like something in the pull request, or you think something should be improved, change it instead of just telling others that what they did wrong and then just leaving the pull request there.

@blattersturm

**Comment by manups4e** [comment]
he told you why and where this pull request was wrong.. he didn't close it because he was waiting for you to update it.. or the new .NET GUI for templates to be finally available for everyone.. clearly you thought that just because you did it.. it must be added?

**Comment by technetium-cfx** [comment]
@SaSiNO97 I'm not quire sure what happened? @blattersturm gave constructive feedback and explicitly pointed out we _do_ greatly appreciate the effort. It's not forgotten about either, why would it be? The pull request is open for updates, and we haven't seen any yet.

**Comment by abhiss** [comment]
I think this should've been merged because it's better than what we have now and future PRs can fix inaccuracies or accommodate the template. I wonder why he closed it.

**Comment by SaSiNO97** [comment]
> I think this should've been merged because it's better than what we have now and future PRs can fix inaccuracies or accommodate the template. 

That's the exact same thing I think.

> I wonder why he closed it.

Because I don't have the time to make the additional changes they requested

**Pull request closed without merging**
