### PR TITLE
Update controls.md

### PR DESCRIPTION
**Pull request by Rex12345678910**

### CODE REVIEW

**Comment by technetium-cfx** [comment]
What? This wasn't wrong to begin with.

```xml
        <Item>
            <Input>INPUT_SCRIPTED_FLY_ZUP</Input>
            <Source>IOMS_PAD_ANALOGBUTTON</Source>
            <Parameters>
                <Item>L2_INDEX</Item>
            </Parameters>
        </Item>
        <Item>
            <Input>INPUT_SCRIPTED_FLY_ZDOWN</Input>
            <Source>IOMS_PAD_ANALOGBUTTON</Source>
            <Parameters>
                <Item>R2_INDEX</Item>
            </Parameters>
        </Item>
```

**Comment by Rex12345678910** [comment]
I have no idea I just want to change the key assignment so the controller
doesn't trigger

Technetium <notifications@github.com> schrieb am Mo., 14. Dez. 2020, 22:15:

**Comment by technetium-cfx** [comment]
And changing the documentation is doing that how?

**Comment by Rex12345678910** [comment]
I was directed here by gta 5 cargo plane mod.  That was in the config




208

207

First parameter is attach or detach cargo control, second is get inside the
cargo bay control.

You can use any controls from here:
https://docs.fivem.net/docs/game-references/controls/#controls





 And from the side I am directed there and then I thought I have to change
that to get a different control, unfortunately I can't speak English very
well, I do everything via Google.
https://github.com/citizenfx/fivem-docs/edit/master/content/docs/game-references/controls.md

Technetium <notifications@github.com> schrieb am Mo., 14. Dez. 2020, 22:21:

**Comment by technetium-cfx** [comment]
Please ask the author of the mod what to do. This is just documentation, it won't change your game settings 🙂

**Comment by Rex12345678910** [comment]
Oh Thank you very much now I know

Technetium <notifications@github.com> schrieb am Mo., 14. Dez. 2020, 23:04:

**Pull request closed without merging**
