### PR TITLE
Create explosionEvent.md

### PR DESCRIPTION
**Pull request by hassony18**

### CODE REVIEW

**Comment by tabarra** [comment]
Thanks for the PR.  
Could you please add an note warning server admins to NOT ban someone automatically when receiving this event?  
Due to the `AddOwnedExplosion()` native, some modders spoof the source of the explosions.

**Comment by tabarra** [comment]
Also, feel free to attack (or even copy) this part of my code where I give an translation table for the explosion types:  
https://github.com/tabarra/txAdmin/blob/master/scripts/sv_logger.js#L158  
  
And make sure to say that sometimes there are ghost explosions going around with damage scale, camera shake and etc being 0 or false.

**Comment by hassony18** [comment]
Updated!

**Comment by tabarra** [comment]
feel free to copy my reasons array, its more complete (including the DONTCARE).

**Comment by hassony18** [comment]
List updated.

**Comment by hassony18** [comment]
Can I at least know why most of my PRs were closed for absolutely no reason?

**Comment by blattersturm** [comment]
Event docs are going to be moved out from the repository, adding new event docs therefore is out of scope. Not sure how that is "no reason".

**Comment by hassony18** [comment]
And how am I supposed to know that you were going to move events' documentations out of the repository? It'd be cool if you actually state *that reason* before closing the PR and not after I ask for that. Quoting me like if I was an absolute idiot and wondering how I didn't get your imaginary reason is not *that appropriate*. Thanks so much...

**Comment by blattersturm** [comment]
What? The PRs were batch-closed, there's no tick in the GitHub UI to add a message to all of them. You could have known as well by following the main repository which had these documentation entries and a tool for generating them added a week ago or so.

Also, quoting? That only happens because I'm replying by email.

**Comment by hassony18** [comment]
When I said quoting I meant the "no reason" you typed. However, everything is cool.  I have started to use github just to help improving fivem's docs so I am just not that experienced with using it (yet). Therefore, I have absolutely no idea where I can find the information you've just stated. 

Cheers and sorry for the misunderstanding...

**Pull request closed without merging**
