### PR TITLE
Add weapon models

### PR DESCRIPTION
**Pull request by 4mmonium**
I generated the file using C#. 
Weapon icons are something that I plan to add in the following weeks.

Data has been gathered from:
https://gist.github.com/root-cause/3f29d38179b12245a003fb4fff615335#file-v2802-weapon-data-json

Thanks to root-cause for the data.

### CODE REVIEW

**Comment by AvarianKnight** [comment]
Few things from testing this:

This should probably go the route that #447 has gone and display this completely as html instead of using markdown tables.

This should remove the extra table of contents since hugo already adds that for us.

**Comment by ahcenezdh** [comment]
Once #447 is done/merged going to take care of this.

**Comment by colistro123** [comment]
Hi, I have updated this to match @ahcenezdh's style in his PR #447. Credits for css styling go to him.
image

I rendered this using my browser.

**Comment by ahcenezdh** [comment]
> Hi, I have updated this to match @ahcenezdh's style in his PR #447. Credits for css styling go to him.
> 
> image
> 
> I rendered this using my browser.

Oh nice! if you want to test with the docs, you can compile it with #417

**Comment by colistro123** [comment]
Added missing images, looks like this on hugo, thanks to ahcenezdh for the hugo build script.

image

**Comment by colistro123** [comment]
Rebased the branch to contain pickup hashes and radiostations in an `_index.md` file since there was a merge conflict.

**Pull request merged**
