### PR TITLE
feat(doc/coding): new guideline

### PR DESCRIPTION
**Pull request by PsychoShock**
Should handle the basics on coding guidelines.

### CODE REVIEW

**Review by colistro123 — CHANGES_REQUESTED** [review]
Hi, I've left a few comments. Aditionally, I'm a bit confused about what you mean by 'coding guidelines' here. Generally, coding guidelines are standards to ensure code is concise and to facilitate easier collaboration among team members, given that everyone might have different coding styles.

For example, Python has the [PEP 8 coding convention](https://peps.python.org/pep-0008/). While Lua doesn't have a widely recognized style guide, LuaRocks provides its [own style guide](https://github.com/luarocks/lua-style-guide).

**Comment by PsychoShock** [comment]
> Aditionally, I'm a bit confused about what you mean by 'coding guidelines' here. Generally, coding guidelines are standards to ensure code is concise and to facilitate easier collaboration among team members, given that everyone might have different coding styles.

Should I just change the structure to method signature then and move this to scripting-ref (https://github.com/citizenfx/fivem-docs/pull/463)?

**Comment by colistro123** [comment]
> > Aditionally, I'm a bit confused about what you mean by 'coding guidelines' here. Generally, coding guidelines are standards to ensure code is concise and to facilitate easier collaboration among team members, given that everyone might have different coding styles.
> 
> Should I just change the structure to method signature then 

I'm not sure what you mean by 'method signature' in this context.

> move this to scripting-ref (#463)?

I think the main idea is that the title of this is wrong. It looks more like a 'Getting Started with FiveM Development' guide. I would focus on improving the current pages instead of changing the structure of the documentation, since it might be structured that way for a reason. Just a suggestion! 😊

**Comment by AvarianKnight** [comment]
None of this seems to be related to coding guidelines, this should go over best practices for resources, like secure your events, check the data sent from the client, etc.

**Pull request closed without merging**
