### PR TITLE
updated more data file examples and descriptions

### PR DESCRIPTION
**Pull request by ook3D**
before merging this, im not 100% on the train ones, could someone double check for me? thanks

### CODE REVIEW

**Comment by 4mmonium** [comment]
Looks good to me, by the way `gta5.meta` (`common.rpf\data\levels\gta5\gta5.meta`)  and `content.xml` (`update\update_retail.rpf\dlc_patch\mpheist\content.xml`) both contain a lot of entries for this kind of stuff.

Nice job finding those 😀

**Comment by 4mmonium** [comment]
Hi, I was wondering if you're planning to add any additional stuff to your PR or if I should just merge, thanks!

**Comment by ook3D** [comment]
> Hi, I was wondering if you're planning to add any additional stuff to your PR or if I should just merge, thanks! porbably should just merge it for now, ill make a PR later with more stuff

**Comment by 4mmonium** [comment]
> > Hi, I was wondering if you're planning to add any additional stuff to your PR or if I should just merge, thanks! porbably should just merge it for now, ill make a PR later with more stuff

Great, thank you!

**Pull request merged**
