### PR TITLE
Update _index.md

### PR DESCRIPTION
**Pull request by hassony18**

### CODE REVIEW

**Comment by cerium-cfx** [comment]
This PR is broken until https://github.com/citizenfx/fivem-docs/pull/108, https://github.com/citizenfx/fivem-docs/pull/106 and https://github.com/citizenfx/fivem-docs/pull/105 are merged

**Comment by hassony18** [comment]
Included events in PR #119 and #118

**Comment by hassony18** [comment]
Hey, you apparently merged this PR without merging the other events
like explosionEvent entityCreated entityCreating entityRemoved
playerEnteredScope playerLeftScope so the PR is broken!

**Comment by stannum-cfx** [comment]
No? They’re all merged.

**Comment by hassony18** [comment]
I meant these ones:
https://github.com/citizenfx/fivem-docs/pull/112
https://github.com/citizenfx/fivem-docs/pull/113
https://github.com/citizenfx/fivem-docs/pull/114
https://github.com/citizenfx/fivem-docs/pull/117
https://github.com/citizenfx/fivem-docs/pull/118
https://github.com/citizenfx/fivem-docs/pull/122
https://github.com/citizenfx/fivem-docs/pull/119
https://github.com/citizenfx/fivem-docs/pull/121

Most of them were closed for the reason that you weren't going to add new
events but apparently that got changed? So I don't know if you would like
to merge them now...

**Pull request merged**
