### PR TITLE
Update controls.md

### PR DESCRIPTION
**Pull request by CollectivelyCode**

### CODE REVIEW

**Comment by technetium-cfx** [comment]
Huh, why? It's used as an escape character here.

**Comment by CollectivelyCode** [comment]
It shows up in the docs. You can see the backlash.

**Comment by FlawwsX** [comment]
You can't: 
image

**Comment by technetium-cfx** [comment]
Ah, in the sidebar only. Would have been useful if you had mentioned that 😛

**Comment by CollectivelyCode** [comment]
Oh, my bad.

**Pull request closed without merging**
